import type { Mod } from '../types';

const now = Date.now();
const day = 86_400_000;

export const MOCK_MODS: Mod[] = [
  {
    id: 'mock-1',
    title: 'Better Survival Pack',
    slug: 'better-survival-pack',
    thumbnail: 'https://picsum.photos/seed/bsp/400/250',
    shortDesc: 'Enhance your survival experience with new tools, weapons, and game mechanics.',
    longDesc: `Better Survival Pack overhauls the core survival experience in Minecraft Bedrock. This comprehensive addon adds over 30 new crafting recipes, 12 new tools, and 8 unique weapons that fit seamlessly into the vanilla game.\n\nKey features include:\n- New tier of tools between diamond and netherite\n- Craftable backpacks for extra storage\n- Enhanced food system with cooking mechanics\n- New ore generation for rare materials\n- Fully compatible with vanilla multiplayer`,
    author: 'CraftMaster99',
    tags: ['survival', 'tools', 'crafting'],
    type: 'mcaddon',
    createdAt: now - day * 2,
    versions: [
      { version: '1.3.0', changelog: 'Added backpack system and new food mechanics', date: now - day * 2 },
      { version: '1.2.0', changelog: 'Added new ore tier and 8 weapons', date: now - day * 15 },
      { version: '1.0.0', changelog: 'Initial release', date: now - day * 30 },
    ],
    screenshots: [
      'https://picsum.photos/seed/bsp1/800/450',
      'https://picsum.photos/seed/bsp2/800/450',
      'https://picsum.photos/seed/bsp3/800/450',
    ],
    gumroadUrl: 'https://gumroad.com',
    downloadCount: 24600,
  },
  {
    id: 'mock-2',
    title: 'Ultra Shader World',
    slug: 'ultra-shader-world',
    thumbnail: 'https://picsum.photos/seed/usw/400/250',
    shortDesc: 'A stunning pre-built world showcasing ultra-realistic shader lighting effects.',
    longDesc: `Ultra Shader World is a handcrafted Minecraft Bedrock world designed specifically to showcase shader capabilities. Every biome has been carefully optimized for maximum visual impact.\n\nWhat's included:\n- 4 distinct showcase areas (forest, ocean, mountains, city)\n- Pre-configured shader settings\n- Cinematic camera paths\n- Custom resource pack included\n- Compatible with most popular shader packs`,
    author: 'PixelArtist_X',
    tags: ['shaders', 'world', 'showcase'],
    type: 'mcworld',
    createdAt: now - day * 5,
    versions: [
      { version: '2.0.0', changelog: 'Added city showcase area and cinematic paths', date: now - day * 5 },
      { version: '1.0.0', changelog: 'Initial world release', date: now - day * 45 },
    ],
    screenshots: [
      'https://picsum.photos/seed/usw1/800/450',
      'https://picsum.photos/seed/usw2/800/450',
    ],
    gumroadUrl: 'https://gumroad.com',
    downloadCount: 18900,
  },
  {
    id: 'mock-3',
    title: 'PvP Arena Pack',
    slug: 'pvp-arena-pack',
    thumbnail: 'https://picsum.photos/seed/pvp/400/250',
    shortDesc: 'Competitive PvP addon with balanced classes, custom arenas, and kill streaks.',
    longDesc: `PvP Arena Pack transforms Minecraft Bedrock into a competitive battleground. Choose from 6 unique classes, each with special abilities and custom equipment sets.\n\nFeatures:\n- 6 balanced PvP classes (Warrior, Archer, Mage, Assassin, Tank, Medic)\n- 4 custom arena maps included\n- Kill streak rewards\n- Scoreboard tracking\n- Anti-lag optimizations for multiplayer`,
    author: 'BattleKing_Official',
    tags: ['pvp', 'competitive', 'arena'],
    type: 'mcaddon',
    createdAt: now - day * 8,
    versions: [
      { version: '3.1.0', changelog: 'Added Medic class and anti-lag optimizations', date: now - day * 8 },
      { version: '3.0.0', changelog: 'Complete class rebalance', date: now - day * 25 },
    ],
    screenshots: [
      'https://picsum.photos/seed/pvp1/800/450',
      'https://picsum.photos/seed/pvp2/800/450',
      'https://picsum.photos/seed/pvp3/800/450',
    ],
    gumroadUrl: 'https://gumroad.com',
    downloadCount: 31200,
  },
  {
    id: 'mock-4',
    title: 'Clean UI Redesign',
    slug: 'clean-ui-redesign',
    thumbnail: 'https://picsum.photos/seed/cui/400/250',
    shortDesc: 'A minimalist HUD and menu redesign that keeps Minecraft clean and modern.',
    longDesc: `Clean UI Redesign strips away the visual clutter of the default Minecraft UI and replaces it with a sleek, modern aesthetic that keeps everything readable and beautiful.\n\nWhat changes:\n- Redesigned hotbar with cleaner icons\n- Minimal health and hunger bars\n- Transparent inventory with blur effect\n- Custom chat UI\n- Streamlined settings menus\n- Works on all screen sizes`,
    author: 'DesignCraft_Studio',
    tags: ['ui', 'hud', 'minimal'],
    type: 'mcpack',
    createdAt: now - day * 1,
    versions: [
      { version: '1.1.0', changelog: 'Added transparent inventory and chat redesign', date: now - day * 1 },
      { version: '1.0.0', changelog: 'Initial release', date: now - day * 20 },
    ],
    screenshots: [
      'https://picsum.photos/seed/cui1/800/450',
      'https://picsum.photos/seed/cui2/800/450',
    ],
    gumroadUrl: 'https://gumroad.com',
    downloadCount: 8750,
  },
  {
    id: 'mock-5',
    title: 'Mob Expansion Addon',
    slug: 'mob-expansion-addon',
    thumbnail: 'https://picsum.photos/seed/mea/400/250',
    shortDesc: 'Adds 25+ new creatures to the overworld, nether, and end dimensions.',
    longDesc: `Mob Expansion Addon populates your Minecraft world with dozens of new creatures, each with unique behaviors, loot tables, and spawn conditions.\n\nNew mobs include:\n- Overworld: Dire Wolf, Forest Sprite, Rock Golem, Swamp Hag\n- Nether: Magma Titan, Soul Wisp, Lava Leech\n- End: Void Stalker, Chorus Elemental\n- Ocean: Deep Lurker, Coral Serpent\n- All mobs have custom sounds and animations`,
    author: 'MobCrafter_Dev',
    tags: ['mobs', 'survival', 'creatures'],
    type: 'mcaddon',
    createdAt: now - day * 12,
    versions: [
      { version: '2.2.0', changelog: 'Added ocean mobs and custom sounds', date: now - day * 12 },
      { version: '2.0.0', changelog: 'End dimension mobs added', date: now - day * 40 },
      { version: '1.0.0', changelog: 'Initial release with overworld mobs', date: now - day * 90 },
    ],
    screenshots: [
      'https://picsum.photos/seed/mea1/800/450',
      'https://picsum.photos/seed/mea2/800/450',
      'https://picsum.photos/seed/mea3/800/450',
      'https://picsum.photos/seed/mea4/800/450',
    ],
    gumroadUrl: 'https://gumroad.com',
    downloadCount: 42100,
  },
  {
    id: 'mock-6',
    title: 'Medieval Kingdom World',
    slug: 'medieval-kingdom-world',
    thumbnail: 'https://picsum.photos/seed/mkw/400/250',
    shortDesc: 'A massive pre-built medieval kingdom with castles, towns, and dungeons.',
    longDesc: `Medieval Kingdom World is a hand-built map spanning over 3000x3000 blocks. Explore a living world filled with towns, castles, dungeons, and hidden secrets.\n\nMap highlights:\n- Capital city with over 200 buildings\n- 5 distinct regional towns\n- 3 explorable castle complexes\n- 8 underground dungeons with custom loot\n- Fully lore-written signs and books\n- Compatible with survival mode`,
    author: 'WorldBuilder_Pro',
    tags: ['world', 'medieval', 'adventure'],
    type: 'mcworld',
    createdAt: now - day * 20,
    versions: [
      { version: '1.5.0', changelog: 'Added eastern region and 2 new dungeons', date: now - day * 20 },
      { version: '1.0.0', changelog: 'Initial world release', date: now - day * 75 },
    ],
    screenshots: [
      'https://picsum.photos/seed/mkw1/800/450',
      'https://picsum.photos/seed/mkw2/800/450',
      'https://picsum.photos/seed/mkw3/800/450',
    ],
    gumroadUrl: 'https://gumroad.com',
    downloadCount: 15600,
  },
  {
    id: 'mock-7',
    title: 'Fun Mini Games Pack',
    slug: 'fun-mini-games-pack',
    thumbnail: 'https://picsum.photos/seed/fmg/400/250',
    shortDesc: 'Collection of 8 fun mini-games perfect for playing with friends.',
    longDesc: `Fun Mini Games Pack bundles 8 complete mini-games into a single addon, perfect for friend groups and servers.\n\nIncluded games:\n1. Spleef Arena\n2. Parkour Challenge (50 levels)\n3. Murder Mystery\n4. Bed Wars (2-8 players)\n5. Sky Wars\n6. Hunger Games\n7. TNT Run\n8. Dropper Challenge\n\nAll games include custom scoreboards and restart systems.`,
    author: 'FunGames_Studio',
    tags: ['minigames', 'fun', 'multiplayer'],
    type: 'mcworld',
    createdAt: now - day * 3,
    versions: [
      { version: '2.0.0', changelog: 'Added Bed Wars and Sky Wars', date: now - day * 3 },
      { version: '1.0.0', changelog: 'Initial 6-game release', date: now - day * 50 },
    ],
    screenshots: [
      'https://picsum.photos/seed/fmg1/800/450',
      'https://picsum.photos/seed/fmg2/800/450',
    ],
    gumroadUrl: 'https://gumroad.com',
    downloadCount: 27300,
  },
  {
    id: 'mock-8',
    title: 'Automation Machines Addon',
    slug: 'automation-machines-addon',
    thumbnail: 'https://picsum.photos/seed/ama/400/250',
    shortDesc: 'Industrial-style machines for automating mining, farming, and crafting.',
    longDesc: `Automation Machines Addon brings factory-style automation to Minecraft Bedrock. Build complex production chains to automate resource gathering and processing.\n\nMachines included:\n- Auto-Miner: Drills resources automatically\n- Crop Harvester: Automated farming\n- Item Sorter: Organizes chests by category\n- Auto-Crafter: Crafts items from recipes\n- Energy Conduit: Powers all machines\n- Storage Controller: Unified item management`,
    author: 'TechBuild_Dev',
    tags: ['automation', 'machines', 'tech'],
    type: 'mcaddon',
    createdAt: now - day * 18,
    versions: [
      { version: '1.4.0', changelog: 'Added Energy Conduit and Storage Controller', date: now - day * 18 },
      { version: '1.0.0', changelog: 'Initial release', date: now - day * 60 },
    ],
    screenshots: [
      'https://picsum.photos/seed/ama1/800/450',
      'https://picsum.photos/seed/ama2/800/450',
      'https://picsum.photos/seed/ama3/800/450',
    ],
    gumroadUrl: 'https://gumroad.com',
    downloadCount: 19800,
  },
  {
    id: 'mock-9',
    title: 'Magic Spells Addon',
    slug: 'magic-spells-addon',
    thumbnail: 'https://picsum.photos/seed/msa/400/250',
    shortDesc: 'Cast powerful spells using a new magic system with 40+ unique abilities.',
    longDesc: `Magic Spells Addon introduces a fully featured magic system to Minecraft Bedrock. Learn spells, level up your magic skill, and unleash devastating abilities.\n\nSystem features:\n- 40+ unique spells across 5 schools (Fire, Ice, Lightning, Nature, Shadow)\n- Spell progression system\n- Craftable magic staves and wands\n- Mana resource management\n- Spell combination combos\n- Balanced for survival mode`,
    author: 'WizardCraft_99',
    tags: ['magic', 'rpg', 'spells'],
    type: 'mcaddon',
    createdAt: now - day * 7,
    versions: [
      { version: '1.6.0', changelog: 'Added Shadow school and combo system', date: now - day * 7 },
      { version: '1.0.0', changelog: 'Initial magic system release', date: now - day * 55 },
    ],
    screenshots: [
      'https://picsum.photos/seed/msa1/800/450',
      'https://picsum.photos/seed/msa2/800/450',
    ],
    gumroadUrl: 'https://gumroad.com',
    downloadCount: 33700,
  },
];
